@REM Generated By GPT
@echo off
setlocal enabledelayedexpansion
title Project Runner

if "%1"=="" (
    echo Usage: %0 ^<command^>
    echo.
    echo Available commands: api, ui, docker, docs, format, build, test, coverage, install
    exit /b 1
)

set CMD=%1

if /i "%CMD%"=="api" goto api
if /i "%CMD%"=="ui" goto ui
if /i "%CMD%"=="docker" goto docker
if /i "%CMD%"=="docs" goto docs
if /i "%CMD%"=="format" goto format
if /i "%CMD%"=="build" goto build
if /i "%CMD%"=="test" goto test
if /i "%CMD%"=="coverage" goto coverage
if /i "%CMD%"=="install" goto install

echo Invalid command: %CMD%
exit /b 1

:api
echo Running API (Development)...
dotnet run --project core\test\Baked.Test.Application
goto end

:ui
echo Starting Playground (Development)...
cd ui
npm run dev
cd ..
goto end

:docker
echo Running Docker (Production)...
docker compose up --build
goto end

:docs
echo Running Docs...
cd docs\.theme
npm run dev
cd ..
goto end

:format
echo Formatting code...
cd core
dotnet format --verbosity normal
cd ..
cd ui
npm run lint -- --fix
cd ..
cd docs\.theme
npm run lint -- --fix
cd ..\..
goto end

:build
echo Building projects...
cd core
dotnet build
cd ..
cd ui
npm run build
cd ..
goto end

:test
echo Running tests...
cd core
dotnet test --logger quackers
cd ..
cd ui
set BUILD_SILENT=1
npm test
cd ..
goto end

:coverage
echo Generating coverage report...
cd core
if exist .coverage rmdir /s /q .coverage
dotnet test -c Release --collect:"XPlat Code Coverage" --logger trx --results-directory .coverage --settings test\runsettings.xml
dotnet reportgenerator -reports:.coverage\*\coverage.cobertura.xml -targetdir:.coverage\html
start .coverage\html\index.html
cd ..
goto end

:install
echo Installing dependencies...
cd docs\.theme && npm i && cd ..\..
cd ui && npm i && cd ..
cd core\test\Baked.Test.LoadTest && npm i && cd ..\..\..
cd core\test\Baked.Test.StubApi && npm i && cd ..\..\..
goto end

:end
echo Done.
