using Baked.IdCodingStyle;
using Baked.IdCodingStyle.AutoGenerated;

namespace Baked;

public static class AutoGeneratedIdCodingStyleExtensions
{
    public static AutoGeneratedIdCodingStyeFeature AutoGenerated(this IdCodingStyleConfigurator _) =>
        new();
}