using Baked.CodeGeneration;
using Baked.Domain.Model;

namespace Baked.IdCodingStyle.AutoGenerated;

public class AutoGeneratedIdMapperTemplate(TypeModel typeModel) : CodeTemplateBase
{
    protected override IEnumerable<string> Render() =>
        [IdMapper()];

    string IdMapper() => $$"""
        namespace AutoGenerated;

        public class {{typeModel.Name}}IdMapper : IIdMapper
        {
            public void Configure(AutoPersistenceModel model)
            {
                model.Override<{{typeModel.CSharpFriendlyFullName}}>(x =>
                    x.Id(e => e.Id).CustomType<AutoGeneratedIdUserType>().GeneratedBy.Custom<AutoGeneratedIdGenerator>()
                );
            }
        }
    """;
}