using Baked.Business;

namespace Baked.CodingStyle.Id;

public static class IdCodingStyleExtensions
{
    public static IdCodingStyeFeature Id(this CodingStyleConfigurator _) =>
        new();

    public static void AutoGenerated(this IdAttribute id) =>
        id.Orm = new(typeof(IdGuidUserType)) { IdentifierGenerator = typeof(IdGuidGenerator) };

    public static void AutoIncrement(this IdAttribute id) =>
        id.Orm = new(typeof(IdIntUserType)) { IdentifierGenerator = typeof(NHibernate.Id.IdentityGenerator) };

    public static void Assigned(this IdAttribute id) =>
        id.Orm = new(typeof(IdStringUserType)) { IdentifierGenerator = typeof(NHibernate.Id.Assigned) };
}