using Baked.Business;

namespace Baked.CodingStyle.Id;

public static class IdCodingStyleExtensions
{
    public static IdCodingStyeFeature Id(this CodingStyleConfigurator _) =>
        new();

    // TODO change these to property extensions with .Net 10 upgrade
    public static IdAttribute.OrmConfig AutoGenerated(this IdAttribute _) =>
        new(typeof(IdGuidUserType)) { IdentifierGenerator = typeof(IdGuidGenerator) };

    public static IdAttribute.OrmConfig AutoIncrement(this IdAttribute _) =>
        new(typeof(IdIntUserType)) { IdentifierGenerator = typeof(NHibernate.Id.IdentityGenerator) };

    public static IdAttribute.OrmConfig Assigned(this IdAttribute _) =>
        new(typeof(IdStringUserType)) { IdentifierGenerator = typeof(NHibernate.Id.Assigned) };
}