using Baked.CodingStyle.Id;
using Baked.Playground.Orm;

using NHConfiguration = NHibernate.Cfg.Configuration;

namespace Baked.Test.Id;

public class ConfiguringAutoGeneratedId : TestSpec
{
    // TODO validate id generator
    [Test]
    public void Id_is_always_guid_id_user_type()
    {
        var configuration = GiveMe.The<NHConfiguration>();

        configuration.GetClassMapping(typeof(Entity)).Identifier.Type.Name.ShouldBe(nameof(IdGuidUserType));
    }

    [Test]
    public void Id_is__property_named_Id()
    {
        var configuration = GiveMe.The<NHConfiguration>();

        var actual = configuration.GetClassMapping(typeof(Entity)).Identifier.ColumnIterator.FirstOrDefault();
        actual.ShouldNotBeNull();
        actual.Text.ShouldBe("Id");
    }
}